-- Question 38:- Aggregation > Weather Observation Station 14

SELECT TRUNCATE(MAX(LAT_N), 4)
FROM STATION
WHERE LAT_N < 137.2345;

-- Question 38:- Aggregation > Weather Observation Station 15

-- SELECT LONG_W 
-- FROM STATION
-- WHERE (SELECT * FROM STATION WHERE LAT_N < 137.2345);
-- IT DOESN'T WORK

SELECT ROUND(LONG_W, 4)
FROM STATION
WHERE LAT_N < 137.2345
ORDER BY LAT_N DESC
LIMIT 1;