-- Question 11: - Weather Observation 6
 
-- WHEN LANGUAGE IS DB2 [NOTE:- DB2 DOESN'T REGEXP.]
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE 'A%' OR 
      CITY LIKE 'E%' OR
      CITY LIKE 'I%' OR
      CITY LIKE 'O%' OR
      CITY LIKE 'U%';
    
-- IN MYSQL
SELECT DISTINCT CITY 
FROM STATION 
WHERE CITY REGEXP '^[AEIOU]';